// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIqs5Zau_tqtzbiPXt6L7-laJc5EW2FKw',
    appId: '1:229003939699:web:2f5ffbd5a8936469a73f06',
    messagingSenderId: '229003939699',
    projectId: 'testebd-e96ed',
    authDomain: 'testebd-e96ed.firebaseapp.com',
    storageBucket: 'testebd-e96ed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBac4oDAvMDY9ZIt5mFwedLSRpHTummRUM',
    appId: '1:229003939699:android:cadd0f026c3fe0fba73f06',
    messagingSenderId: '229003939699',
    projectId: 'testebd-e96ed',
    storageBucket: 'testebd-e96ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7SCq26yOePcejLJxs6Gxz2FaWrD_1h3o',
    appId: '1:229003939699:ios:c7dc96a07b1228cfa73f06',
    messagingSenderId: '229003939699',
    projectId: 'testebd-e96ed',
    storageBucket: 'testebd-e96ed.firebasestorage.app',
    iosBundleId: 'com.example.autotesteflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7SCq26yOePcejLJxs6Gxz2FaWrD_1h3o',
    appId: '1:229003939699:ios:c7dc96a07b1228cfa73f06',
    messagingSenderId: '229003939699',
    projectId: 'testebd-e96ed',
    storageBucket: 'testebd-e96ed.firebasestorage.app',
    iosBundleId: 'com.example.autotesteflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIqs5Zau_tqtzbiPXt6L7-laJc5EW2FKw',
    appId: '1:229003939699:web:751de9731eb6389aa73f06',
    messagingSenderId: '229003939699',
    projectId: 'testebd-e96ed',
    authDomain: 'testebd-e96ed.firebaseapp.com',
    storageBucket: 'testebd-e96ed.firebasestorage.app',
  );
}
